// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCoat.proto

package smartCoat;

public interface BooleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartCoat.BooleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool booleanRepVal = 1;</code>
   */
  boolean getBooleanRepVal();
}
