// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCoat.proto

package smartCoat;

public interface BooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartCoat.BooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool booleanVal = 1;</code>
   */
  boolean getBooleanVal();
}
