// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCoat.proto

package smartCoat;

public interface IntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartCoat.IntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intValue = 1;</code>
   */
  int getIntValue();
}
