// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCoat.proto

package smartCoat;

public interface IntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartCoat.IntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intRespValue = 1;</code>
   */
  int getIntRespValue();
}
