// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartCoat.proto

package smartCoat;

public final class smartCoatImpl {
  private smartCoatImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartCoat_BooleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartCoat_BooleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartCoat_BooleanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartCoat_BooleanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartCoat_IntRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartCoat_IntRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartCoat_IntResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartCoat_IntResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017smartCoat.proto\022\tsmartCoat\"$\n\016BooleanR" +
      "equest\022\022\n\nbooleanVal\030\001 \001(\010\"(\n\017BooleanRes" +
      "ponse\022\025\n\rbooleanRepVal\030\001 \001(\010\"\036\n\nIntReque" +
      "st\022\020\n\010intValue\030\001 \001(\005\"#\n\013IntResponse\022\024\n\014i" +
      "ntRespValue\030\001 \001(\0052\227\001\n\020smartCoatService\022G" +
      "\n\014turnOnSwitch\022\031.smartCoat.BooleanReques" +
      "t\032\032.smartCoat.BooleanResponse\"\000\022:\n\007setTe" +
      "mp\022\025.smartCoat.IntRequest\032\026.smartCoat.In" +
      "tResponse\"\000B\034\n\tsmartCoatB\rsmartCoatImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartCoat_BooleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartCoat_BooleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartCoat_BooleanRequest_descriptor,
        new java.lang.String[] { "BooleanVal", });
    internal_static_smartCoat_BooleanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartCoat_BooleanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartCoat_BooleanResponse_descriptor,
        new java.lang.String[] { "BooleanRepVal", });
    internal_static_smartCoat_IntRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartCoat_IntRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartCoat_IntRequest_descriptor,
        new java.lang.String[] { "IntValue", });
    internal_static_smartCoat_IntResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartCoat_IntResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartCoat_IntResponse_descriptor,
        new java.lang.String[] { "IntRespValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
