// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface BooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.BooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool boolVal = 1;</code>
   */
  boolean getBoolVal();
}
