// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface sgBooleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.sgBooleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool boolRespVal = 1;</code>
   */
  boolean getBoolRespVal();
}
