// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface sgBooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.sgBooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool boolVal = 1;</code>
   */
  boolean getBoolVal();
}
