// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface sgIntResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.sgIntResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intResponseValue = 1;</code>
   */
  int getIntResponseValue();
}
