// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface sgIntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.sgIntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intVal = 1;</code>
   */
  int getIntVal();
}
