// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface sgStringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.sgStringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringVal = 1;</code>
   */
  java.lang.String getStringVal();
  /**
   * <code>string stringVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValBytes();
}
