// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartGlasses.proto

package smartGlasses;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartGlasses.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringRespVal = 1;</code>
   */
  java.lang.String getStringRespVal();
  /**
   * <code>string stringRespVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringRespValBytes();
}
