// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWatch.proto

package smartWatch;

public interface BooleanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWatch.BooleanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool booleanVal = 1;</code>
   */
  boolean getBooleanVal();
}
