// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWatch.proto

package smartWatch;

public interface BooleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWatch.BooleanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool booleanRepVal = 1;</code>
   */
  boolean getBooleanRepVal();
}
