// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWatch.proto

package smartWatch;

public interface IntRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWatch.IntRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 intValue = 1;</code>
   */
  int getIntValue();
}
