// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWatch.proto

package smartWatch;

public final class smartWatchImpl {
  private smartWatchImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWatch_BooleanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWatch_BooleanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWatch_BooleanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWatch_BooleanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWatch_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWatch_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smartWatch_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smartWatch_StringResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020smartWatch.proto\022\nsmartWatch\"$\n\016Boolea" +
      "nRequest\022\022\n\nbooleanVal\030\001 \001(\010\"(\n\017BooleanR" +
      "esponse\022\025\n\rbooleanRepVal\030\001 \001(\010\"\"\n\rString" +
      "Request\022\021\n\tstringVal\030\001 \001(\t\"&\n\016StringResp" +
      "onse\022\024\n\014stringRepVal\030\001 \001(\t2\376\002\n\021smartWatc" +
      "hService\022I\n\014turnOnSwitch\022\032.smartWatch.Bo" +
      "oleanRequest\032\033.smartWatch.BooleanRespons" +
      "e\"\000\022C\n\010setTimer\022\031.smartWatch.StringReque" +
      "st\032\032.smartWatch.StringResponse\"\000\022G\n\nstar" +
      "tTimer\022\032.smartWatch.BooleanRequest\032\033.sma" +
      "rtWatch.BooleanResponse\"\000\022G\n\npauseTimer\022" +
      "\032.smartWatch.BooleanRequest\032\033.smartWatch" +
      ".BooleanResponse\"\000\022G\n\nresetTimer\022\032.smart" +
      "Watch.BooleanRequest\032\033.smartWatch.Boolea" +
      "nResponse\"\000B\036\n\nsmartWatchB\016smartWatchImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_smartWatch_BooleanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smartWatch_BooleanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWatch_BooleanRequest_descriptor,
        new java.lang.String[] { "BooleanVal", });
    internal_static_smartWatch_BooleanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smartWatch_BooleanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWatch_BooleanResponse_descriptor,
        new java.lang.String[] { "BooleanRepVal", });
    internal_static_smartWatch_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smartWatch_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWatch_StringRequest_descriptor,
        new java.lang.String[] { "StringVal", });
    internal_static_smartWatch_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_smartWatch_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smartWatch_StringResponse_descriptor,
        new java.lang.String[] { "StringRepVal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
