// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWatch.proto

package smartWatch;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWatch.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringVal = 1;</code>
   */
  java.lang.String getStringVal();
  /**
   * <code>string stringVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringValBytes();
}
