// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartWatch.proto

package smartWatch;

public interface StringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartWatch.StringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stringRepVal = 1;</code>
   */
  java.lang.String getStringRepVal();
  /**
   * <code>string stringRepVal = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringRepValBytes();
}
